# Generated by Django 4.2.13 on 2024-06-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directchat",
            name="profile1",
        ),
        migrations.RemoveField(
            model_name="directchat",
            name="profile2",
        ),
        migrations.AddField(
            model_name="directchat",
            name="profiles",
            field=models.ManyToManyField(to="users.profile"),
        ),
    ]
